// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  changelogDocs: create.doc("changelogDocs", {"v0.0.1.mdx": () => import("../content/changelog/v0.0.1.mdx?collection=changelogDocs"), "v0.0.2.mdx": () => import("../content/changelog/v0.0.2.mdx?collection=changelogDocs"), "v0.0.3.mdx": () => import("../content/changelog/v0.0.3.mdx?collection=changelogDocs"), "v0.0.4.mdx": () => import("../content/changelog/v0.0.4.mdx?collection=changelogDocs"), "v0.0.5.mdx": () => import("../content/changelog/v0.0.5.mdx?collection=changelogDocs"), "v0.0.6.mdx": () => import("../content/changelog/v0.0.6.mdx?collection=changelogDocs"), }),
  docs: create.doc("docs", {"core/hls-engine.mdx": () => import("../content/docs/core/hls-engine.mdx?collection=docs"), "core/mp4-engine.mdx": () => import("../content/docs/core/mp4-engine.mdx?collection=docs"), "core/overview.mdx": () => import("../content/docs/core/overview.mdx?collection=docs"), "core/youtube-engine.mdx": () => import("../content/docs/core/youtube-engine.mdx?collection=docs"), "react/hls-player.mdx": () => import("../content/docs/react/hls-player.mdx?collection=docs"), "react/hooks.mdx": () => import("../content/docs/react/hooks.mdx?collection=docs"), "react/mp4-player.mdx": () => import("../content/docs/react/mp4-player.mdx?collection=docs"), "react/overview.mdx": () => import("../content/docs/react/overview.mdx?collection=docs"), "react/player.mdx": () => import("../content/docs/react/player.mdx?collection=docs"), "react/youtube-player.mdx": () => import("../content/docs/react/youtube-player.mdx?collection=docs"), "guides/custom-controls.mdx": () => import("../content/docs/guides/custom-controls.mdx?collection=docs"), "guides/live-streams.mdx": () => import("../content/docs/guides/live-streams.mdx?collection=docs"), "guides/security.mdx": () => import("../content/docs/guides/security.mdx?collection=docs"), "guides/theming.mdx": () => import("../content/docs/guides/theming.mdx?collection=docs"), "guides/token-auth.mdx": () => import("../content/docs/guides/token-auth.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/introduction.mdx": () => import("../content/docs/getting-started/introduction.mdx?collection=docs"), "getting-started/quick-start.mdx": () => import("../content/docs/getting-started/quick-start.mdx?collection=docs"), "reference/keyboard-shortcuts.mdx": () => import("../content/docs/reference/keyboard-shortcuts.mdx?collection=docs"), "reference/player-controls.mdx": () => import("../content/docs/reference/player-controls.mdx?collection=docs"), "reference/props.mdx": () => import("../content/docs/reference/props.mdx?collection=docs"), "reference/types.mdx": () => import("../content/docs/reference/types.mdx?collection=docs"), "ui/components.mdx": () => import("../content/docs/ui/components.mdx?collection=docs"), "ui/icons.mdx": () => import("../content/docs/ui/icons.mdx?collection=docs"), "ui/overview.mdx": () => import("../content/docs/ui/overview.mdx?collection=docs"), "ui/player-controls.mdx": () => import("../content/docs/ui/player-controls.mdx?collection=docs"), "ui/themes.mdx": () => import("../content/docs/ui/themes.mdx?collection=docs"), }),
};
export default browserCollections;